# Generated by Django 2.2.6 on 2019-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
