# Generated by Django 2.2.6 on 2019-10-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='reminder',
        ),
    ]
