# Generated by Django 2.2.6 on 2019-10-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', to='note.Label'),
        ),
    ]
