# Generated by Django 2.2.6 on 2019-10-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_note_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
