# Generated by Django 2.2.6 on 2019-11-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_note_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_delete',
            new_name='is_trash',
        ),
    ]
